### ISSUE TITLE
编辑器 上传图片异常

### ISSUE THREAD

**Issue by kalsolio** [TDuckCloud/tduck-platform#8]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/14342288/169955197-b4e7ef7d-ea64-4ef0-8c63-953ac7d06303.png">

本地部署测试也是不行

**Comment by JTongChen** [comment]
遇到类似问题，上传图片请求偶现405。有的用户会出现该情况，有的用户又正常。出现问题的用户刷新页面之后，又能正常上传了。以下两图分别为正常上传与错误上传的截图：
![image](https://github.com/TDuckCloud/tduck-platform/assets/17989583/e904a394-b1f0-4ef2-9b84-0fe4a9ba345a)
![image](https://github.com/TDuckCloud/tduck-platform/assets/17989583/127bff0a-21f4-4b92-acaa-9fce220546cc)
